### ISSUE TITLE
Issue with Fiorentina

### ISSUE THREAD

**Issue by andrekaufman** [Regista6/FIFA-23-Automated-SBC-Solving#14]
Thanks for your app, super cool! It has worked great for many SBCs, but it doesn't seem to be able to find players from Fiorentina. 

When including `CLUB = [["Fiorentina"]]`  I get:

```
Python main.py
Processing time create_var: 0.05 seconds
Processing time create_basic_constraints: 0.01 seconds
Traceback (most recent call last):
  File "C:\Users\User\Documents\EA-FC-Automated-SBC-Solving-master\main.py", line 64, in <module>
    final_players = optimize.SBC(df)
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\EA-FC-Automated-SBC-Solving-master\optimize.py", line 10, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\EA-FC-Automated-SBC-Solving-master\optimize.py", line 581, in SBC
    model = create_club_constraint(df, model, player, map_idx, players_grouped, num_cnts)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\EA-FC-Automated-SBC-Solving-master\optimize.py", line 10, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Documents\EA-FC-Automated-SBC-Solving-master\optimize.py", line 128, in create_club_constraint
    expr += players_grouped["Club"].get(map_idx["Club"][club], [])
                                        ~~~~~~~~~~~~~~~^^^^^^
KeyError: 'Fiorentina'
```

When using FIX_PLAYERS, it simply ignores a Fiorentina player. Fixing other players works though.

**Comment by Regista6** [comment]
Thank you so much for your interest!

Can you please share your club dataset and the SBC you are trying to solve?

I think the error is because your dataset doesn't have any players from Fiorentina.

**Comment by andrekaufman** [comment]
Sorry for the late reply. I have players from Fiorentina, and I verified that I entered 'Fiorentina' exactly as it was stated in the .csv dataset file exported with FC Enhancer.

The SBC I was trying to solve was this one: https://www.futbin.com/25/squad-building-challenge/ea/565/Fiorentina%20v%20Lombardia%20FC

I ended up solving it by including players from Lombardia FC, but perhaps there's something worth investigating here. My dataset has slightly changed since, but the underlying issue should still persist: https://files.catbox.moe/gm1qh8.csv

Again, I’m blown away by this tool, using CP-SAT solver for SBCs is nuts man! Quick question though: what’s the correct input for "Player Level: Min Silver"?

**Comment by Regista6** [comment]
Hi,

Apologies for the late reply. I actually was able to solve the SBC with your squad!

<img width="866" alt="image" src="https://github.com/user-attachments/assets/c497ca68-7d43-4181-b615-6559b48b27c4">

Probably there is some issue with the way you are setting the club constraint.

Here are the inputs:

| Requirement                        | Input| Constraint|
|-----------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------|
| # of players from Fiorentina: Min 1 <br> # of players from Lombardia FC: Min 1 | `CLUB = [["Fiorentina"], ["Lombardia FC"]]` <br> `NUM_CLUB = [1,1]` <br> Total players from i^th list >= `NUM_CLUB[i]`                   | `create_club_constraint`        |
|                                   |                                                                                                                                           |                                 |
| Leagues: Max 4                    | `NUM_UNIQUE_LEAGUE = [4, "Max"]` <br> Leagues: Max / Min / Exactly X                                                                      | `create_unique_league_constraint` |
| Same Club Count: Min 2            | `MIN_NUM_CLUB = 2` <br> Same Club Count: Min X / Min X Players from the Same Club                                                        | `create_min_club_constraint`    |
| Rare: Min 2                       | `RARITY_2 = ["Rare"]` <br> `NUM_RARITY_2 = [2]` <br> Total players from i^th Rarity / Color >= `NUM_RARITY_2[i]`                             | `create_rarity_2_constraint`    |
| Squad Rating: Min 75              | `SQUAD_RATING = 75`                                                                                                                      | `create_squad_rating_constraint_3` |
| Team Chemistry: Min 22            | `CHEMISTRY = 22`                                                                                                                         |                                 |
| # of players in squad: 11         | `NUM_PLAYERS = 11`                                                                                                                        |                                 |


`Player Level: Min Silver` -> You can uncomment 

`df = df[df["Color"] != "Bronze"] # Can be used for constraints like Player Quality: Min Silver`  in `preprocess_data_2` in `main.py`.

Please feel free to reach out if you any other questions!!
